name: Preview the frontend

on:
  push:
    branches:
      - '**'
      - '!main'
    paths:
      - 'packages/frontend/**'
  workflow_dispatch:

env:
  RAW_IMAGE_TAG: ghcr.io/${{ github.repository }}-frontend-preview
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Log in to the container registry ${{ env.REGISTRY }}
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - run: |
          echo "IMAGE_TAG=${RAW_IMAGE_TAG,,}" >>${GITHUB_ENV}

      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          file: frontend.Dockerfile
          push: true
          tags: ${{ env.IMAGE_TAG }}:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "IMAGE_TAG=${RAW_IMAGE_TAG,,}" >>${GITHUB_ENV}

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          password: ${{ secrets.DEPLOY_PASSWORD }}
          script: |
            echo ${{ secrets.PAT }} | docker login ${{ env.REGISTRY }} -u USERNAME --password-stdin
            docker stop mod-tham-ngarn-frontend-pv || true && docker rm mod-tham-ngarn-frontend-pv || true
            docker rmi ${{ env.IMAGE_TAG }}:latest
            docker pull ${{ env.IMAGE_TAG }}:latest
            docker run -p 5000:3000 -d --name mod-tham-ngarn-frontend-pv ${{ env.IMAGE_TAG }}:latest
